---
title: "Testing"
---

```{r}
library(haven)
ALQ_J <- read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/ALQ_J.XPT")
INQ_J <- read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/INQ_J.XPT")
LUX_J <- read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/LUX_J.XPT")
DEMO_J <- read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DEMO_J.XPT")
BPX_J <- read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/BPX_J.XPT")
DR1TOT_J = read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DR1TOT_J.XPT")
# DR2TOT_J = read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DR2TOT_J.XPT")
DS1TOT_J = read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DS1TOT_J.XPT")
# DS2TOT_J = read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DS2TOT_J.XPT")
# DSQIDS_J = read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DSQIDS_J.XPT")
DSQTOT_J = read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DSQTOT_J.XPT")
HSQ_J = read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/HSQ_J.XPT")
```

```{r}
FULL <- merge(ALQ_J, BPX_J[,c(1,6)], by = "SEQN", all = TRUE)
FULL <- merge(FULL, INQ_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, DEMO_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, DR1TOT_J, by = "SEQN", all = TRUE)
# FULL <- merge(FULL, DR2TOT_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, DS1TOT_J, by = "SEQN", all = TRUE)
# FULL <- merge(FULL, DS2TOT_J, by = "SEQN", all = TRUE)
# FULL <- merge(FULL, DSQIDS_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, DSQTOT_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, HSQ_J, by = "SEQN", all = TRUE)

FULL[is.na(FULL)] <- -1
# FULL <- merge(FULL, BPX_J, by = "SEQN", all = TRUE)
```

```{r}
# dim(ALQ_J)
# head(ALQ_J)
# colSums(is.na(ALQ_J))
dim(FULL)

colSums(is.na(BPX_J))
# head(LUX_J)
```

```{r}
lm <- lm(BPXPLS ~ .-SEQN, data=FULL)
summary(lm)
```