---
title: "More Testing"
---

```{r}
library(haven)
library(foreach)
# ALQ_J, INQ_J, LUX_J, DEMO_J, BPQ_J, HSQ_J, DUQ_J, WHQ_J, BIOPRO_J, DR1TO, T_J, DS1TOT_J, DSQTOT_J
db <- list("ALQ_J", "INQ_J", "LUX_J", "DEMO_J", "BPQ_J", "HSQ_J", "DUQ_J", "WHQ_J", "BIOPRO_J")
db <- append(db, list("DR1TOT_J", "DS1TOT_J", "DSQTOT_J"))
for(i in db) {
 nam <- paste(i)
 print(paste("Importing:",i))
 assign(nam, read_xpt(paste("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/", i, ".XPT", sep="")))
}
```

```{r}
FULL <- merge(LUX_J[,c("SEQN","LUXCAPM")], DEMO_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, HSQ_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, ALQ_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, INQ_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, DUQ_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, WHQ_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, BIOPRO_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, BPQ_J, by = "SEQN", all = TRUE)

FULL <- merge(FULL, DR1TOT_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, DS1TOT_J, by = "SEQN", all = TRUE)
FULL <- merge(FULL, DSQTOT_J, by = "SEQN", all = TRUE)

FULL <- FULL[!is.na(FULL$LUXCAPM),]
dim(FULL)

FULL[is.na(FULL)] <- -1

```

```{r}
# dim(ALQ_J)
# head(ALQ_J)
# colSums(is.na(ALQ_J))
dim(FULL)

colSums(is.na(LUX_J))
# head(LUX_J)
```

```{r}
lm <- lm(LUXCAPM  ~ .-SEQN, data=FULL)
summary(lm)
```




